CURRENT_generatePatchErrors( 'patchesSep2011Data_time7.mat',...
    'patchesSep2011Data_partialResults_time7.mat',...
    'patchesSep2011Data_results_time7.mat' );

CURRENT_generatePatchErrors( 'patchesSep2011Data_time46.mat',...
    'patchesSep2011Data_partialResults_time46.mat',...
    'patchesSep2011Data_results_time46.mat' )
