%{
CURRENT_generatePatchErrors( 'patchesSep2011Data_time7.mat',...
    'patchesSep2011Data_partialResults_time7.mat',...
    'patchesSep2011Data_results_time7.mat' );

CURRENT_generatePatchErrors( 'patchesSep2011Data_time46.mat',...
    'patchesSep2011Data_partialResults_time46.mat',...
    'patchesSep2011Data_results_time46.mat' )
%}

CURRENT_generatePatchErrors( 'patchesOct2012Data_time4.mat',...
    'patchesOct2012Data_partialResults_time4.mat',...
    'patchesOct2012Data_results_time4.mat' );

CURRENT_generatePatchErrors( 'patchesOct2012Data_time5.mat',...
    'patchesOct2012Data_partialResults_time5.mat',...
    'patchesOct2012Data_results_time5.mat' )